#!/usr/bin/env python3
"""
Deterministic fixture library seeder for CrateMindAI development and testing.

Creates a fake-but-realistic DJ library under a fixture root:
  * ~300 canonical tracks in <root>/logs/processed.db (real schema via db.py)
  * real (tiny, silent) MP3 files with real ID3 tags on disk
  * deliberate issue coverage: missing metadata, junk tags, missing BPM/key,
    suspicious BPM, duplicate pairs, missing files, untracked files, quarantine
  * an enrichment review queue JSONL in the exact pipeline format
  * genuine review queues generated by the REAL pipeline scans afterwards

Never touches any real music library. Root defaults to /app/fixture_library.

Usage:
  python3 scripts/seed_fixture_library.py [--root /app/fixture_library] [--force]
"""
from __future__ import annotations

import argparse
import json
import os
import random
import shutil
import sqlite3
import subprocess
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# Deterministic source data
# ---------------------------------------------------------------------------

SEED = 42

ARTISTS = [
    "Aria Vex", "Bassline Theory", "Carmen Flux", "Deep Meridian", "Echo Parade",
    "Filter Kings", "Groove Assembly", "Helix Nova", "Iris Deluxe", "Jade Circuit",
    "Kilo Watts", "Luna Verde", "Modular Ghost", "Night Cartel", "Opal Motion",
    "Pulse Widow", "Quantum Feels", "Rhythm Salon", "Static Bloom", "Tidal Forms",
    "Umbra Society", "Velvet Rotor", "Wax Prophets", "Xeno Drift", "Yara Sol",
    "Zenith Corp", "Analog Sons", "Berlin Echo", "Copper Waves", "Dune Sirens",
    "Ember Fields", "Frost Motif", "Golden Ratio", "Harbor Lights", "Indigo Set",
    "Jupiter Halls", "Kora Beats", "Lucid Panther", "Metro Fauna", "Neon Harvest",
]

TITLE_WORDS_A = [
    "Midnight", "Solar", "Velvet", "Electric", "Hidden", "Broken", "Golden",
    "Crimson", "Silent", "Rising", "Falling", "Distant", "Neon", "Amber",
    "Frozen", "Burning", "Lost", "Secret", "Wild", "Deep",
]
TITLE_WORDS_B = [
    "Horizon", "Pulse", "Motion", "Echoes", "Gravity", "Mirage", "Voltage",
    "Rapture", "Currents", "Skyline", "Tension", "Bloom", "Signal", "Drift",
    "Orbit", "Cascade", "Empire", "Reverie", "Fracture", "Meridian",
]
VERSIONS = [None, None, None, None, "Extended Mix", "Original Mix", "Club Mix",
            "Radio Edit", "Dub Mix", "Remix"]
GENRES = [
    "House", "Tech House", "Deep House", "Techno", "Melodic Techno",
    "Progressive House", "Afro House", "Drum & Bass", "Disco", "Indie Dance",
]
CAMELOT = [f"{n}{l}" for n in range(1, 13) for l in ("A", "B")]
CAMELOT_TO_MUSICAL = {
    "1A": "Abm", "1B": "B", "2A": "Ebm", "2B": "F#", "3A": "Bbm", "3B": "Db",
    "4A": "Fm", "4B": "Ab", "5A": "Cm", "5B": "Eb", "6A": "Gm", "6B": "Bb",
    "7A": "Dm", "7B": "F", "8A": "Am", "8B": "C", "9A": "Em", "9B": "G",
    "10A": "Bm", "10B": "D", "11A": "F#m", "11B": "A", "12A": "Dbm", "12B": "E",
}

JUNK_TITLE_SUFFIXES = [
    " (Official Video)", " [FREE DOWNLOAD]", " | www.djpromo.club",
    " - Copyright Free", " (OUT NOW!!!)", " ~ visit soundpack.example.com",
]
JUNK_ARTIST_SUFFIXES = [" [promo]", " (www.beatleaks.example)", " OFFICIAL"]

BASE_TIME = datetime(2026, 5, 20, 9, 0, 0, tzinfo=timezone.utc)

# Minimal valid MPEG-1 Layer III frame: 128 kbps, 44.1 kHz, stereo, no padding.
# Frame length = 144 * 128000 / 44100 = 417 bytes.
_MP3_FRAME = b"\xff\xfb\x90\x00" + b"\x00" * 413
_MP3_BODY = _MP3_FRAME * 38  # ~1 second of silence


def write_mp3(path: Path, tags: dict | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(_MP3_BODY)
    if tags:
        from mutagen.id3 import ID3, TALB, TBPM, TCON, TIT2, TKEY, TPE1

        id3 = ID3()
        if tags.get("title"):
            id3.add(TIT2(encoding=3, text=[tags["title"]]))
        if tags.get("artist"):
            id3.add(TPE1(encoding=3, text=[tags["artist"]]))
        if tags.get("album"):
            id3.add(TALB(encoding=3, text=[tags["album"]]))
        if tags.get("genre"):
            id3.add(TCON(encoding=3, text=[tags["genre"]]))
        if tags.get("bpm"):
            id3.add(TBPM(encoding=3, text=[str(tags["bpm"])]))
        if tags.get("key"):
            id3.add(TKEY(encoding=3, text=[tags["key"]]))
        id3.save(path)


def track_path(root: Path, artist: str, title: str, version: str | None) -> Path:
    letter = artist[0].upper()
    name = f"{artist} - {title}"
    if version:
        name += f" ({version})"
    return root / "library" / letter / artist / f"{name}.mp3"


def build_plan(rng: random.Random, root: Path) -> list[dict]:
    """Build the deterministic track plan with issue coverage."""
    plan: list[dict] = []
    used_names: set[str] = set()

    def unique_track() -> tuple[str, str, str | None]:
        while True:
            artist = rng.choice(ARTISTS)
            title = f"{rng.choice(TITLE_WORDS_A)} {rng.choice(TITLE_WORDS_B)}"
            version = rng.choice(VERSIONS)
            key = f"{artist}|{title}|{version}"
            if key not in used_names:
                used_names.add(key)
                return artist, title, version

    def base_row(i: int, kind: str) -> dict:
        artist, title, version = unique_track()
        camelot = rng.choice(CAMELOT)
        bpm = round(rng.uniform(118.0, 132.0), 1)
        if rng.random() < 0.2:
            bpm = round(rng.uniform(85.0, 175.0), 1)
        return {
            "kind": kind,
            "artist": artist,
            "title": title,
            "version": version,
            "album": f"{rng.choice(TITLE_WORDS_B)} EP" if rng.random() < 0.6 else None,
            "genre": rng.choice(GENRES),
            "bpm": bpm,
            "key_camelot": camelot,
            "key_musical": CAMELOT_TO_MUSICAL[camelot],
            "duration": round(rng.uniform(180.0, 480.0), 1),
            "bitrate": rng.choice([320, 320, 320, 256, 192]),
            "status": "ok",
            "quality_tier": rng.choice(["HIGH", "HIGH", "HIGH", "MEDIUM"]),
            "parse_confidence": rng.choice(["HIGH", "HIGH", "MEDIUM"]),
            "processed_at": (BASE_TIME + timedelta(minutes=i * 7)).isoformat(),
            "create_file": True,
        }

    i = 0

    def add(n: int, kind: str, mutate) -> None:
        nonlocal i
        for _ in range(n):
            row = base_row(i, kind)
            mutate(row)
            plan.append(row)
            i += 1

    add(199, "clean", lambda r: None)

    def missing_meta(r):
        r["path_artist"] = r["artist"]
        r["path_title"] = r["title"]
        choice = rng.random()
        if choice < 0.4:
            r["artist"] = None
        elif choice < 0.8:
            r["title"] = None
        else:
            r["artist"] = None
            r["title"] = None
        r["genre"] = None if rng.random() < 0.5 else r["genre"]
        r["status"] = "needs_review"
        r["parse_confidence"] = "LOW"
    add(20, "missing_meta", missing_meta)

    def junk_meta(r):
        r["title"] = r["title"] + rng.choice(JUNK_TITLE_SUFFIXES)
        if rng.random() < 0.4:
            r["artist"] = r["artist"] + rng.choice(JUNK_ARTIST_SUFFIXES)
        r["status"] = "needs_review"
        r["parse_confidence"] = "MEDIUM"
    add(20, "junk_meta", junk_meta)

    def missing_bpm(r):
        r["bpm"] = None
    add(24, "missing_bpm", missing_bpm)

    def missing_key(r):
        r["key_camelot"] = None
        r["key_musical"] = None
    add(19, "missing_key", missing_key)

    def suspicious_bpm(r):
        r["bpm"] = rng.choice([12.0, 15.5, 305.0, 512.0, 999.0, 63.2])
        r["status"] = "needs_review"
    add(6, "suspicious_bpm", suspicious_bpm)

    def missing_file(r):
        r["create_file"] = False
        r["status"] = "error"
        r["error_msg"] = "file missing on disk"
    add(10, "missing_file", missing_file)

    # duplicate pairs: 6 originals + 6 dupes (12 rows)
    for _ in range(6):
        row = base_row(i, "dup_original")
        plan.append(row)
        i += 1
        dup = dict(row)
        dup["kind"] = "dup_copy"
        dup["bitrate"] = 192
        dup["version"] = (row["version"] or "") + " (1)" if row["version"] else "(1)"
        dup["dup_of"] = len(plan) - 1
        dup["status"] = "needs_review"
        plan.append(dup)
        i += 1

    return plan


def seed(root: Path, force: bool) -> None:
    rng = random.Random(SEED)

    if root.exists() and any(root.iterdir()):
        if not force:
            print(f"Refusing to seed non-empty root {root} (use --force).")
            sys.exit(1)
        shutil.rmtree(root)

    # Point pipeline config at the fixture root BEFORE importing db/config.
    os.environ["DJ_MUSIC_ROOT"] = str(root)
    os.environ["CRATEMINDAI_LIBRARY_ROOT"] = str(root)
    sys.path.insert(0, str(PROJECT_ROOT))
    import db as pipeline_db  # noqa: E402

    for sub in ["library", "inbox", "playlists", "logs", "data/intelligence",
                ".BIN/QUARANTINE"]:
        (root / sub).mkdir(parents=True, exist_ok=True)

    plan = build_plan(rng, root)

    # --- files on disk -------------------------------------------------------
    created_files = 0
    for row in plan:
        row["filepath"] = track_path(
            root,
            row.get("path_artist") or row["artist"] or "Unknown Artist",
            row.get("path_title") or row["title"] or "Untitled",
            row["version"],
        )
        if row["create_file"]:
            write_mp3(row["filepath"], {
                "title": row["title"],
                "artist": row["artist"],
                "album": row["album"],
                "genre": row["genre"],
                "bpm": row["bpm"],
                "key": row["key_musical"],
            })
            created_files += 1

    # untracked files: on disk but not in DB
    untracked = []
    for n in range(8):
        p = root / "inbox" / f"promo_drop_{n + 1:02d}.mp3"
        write_mp3(p, {"title": f"Promo Drop {n + 1}", "artist": "Unknown"})
        untracked.append(p)

    # quarantined files
    quarantined = []
    for n in range(3):
        p = root / ".BIN" / "QUARANTINE" / f"quarantined_dup_{n + 1}.mp3"
        write_mp3(p)
        quarantined.append(p)

    # --- database -------------------------------------------------------------
    pipeline_db.init_db()
    db_path = root / "logs" / "processed.db"
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()

    track_ids: list[int] = []
    for row in plan:
        fp = str(row["filepath"])
        cur.execute(
            """
            INSERT INTO tracks (
                filepath, filename, artist, title, album, genre, bpm,
                key_musical, key_camelot, duration_sec, bitrate_kbps,
                filesize_bytes, status, error_msg, processed_at, pipeline_ver,
                quality_tier, parse_confidence
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                fp, row["filepath"].name, row["artist"], row["title"],
                row["album"], row["genre"], row["bpm"], row["key_musical"],
                row["key_camelot"], row["duration"], row["bitrate"],
                row["filepath"].stat().st_size if row["create_file"] else 9_990_000,
                row["status"], row.get("error_msg"), row["processed_at"],
                "1.4.0", row["quality_tier"], row["parse_confidence"],
            ),
        )
        track_ids.append(cur.lastrowid)

        size = row["filepath"].stat().st_size if row["create_file"] else 9_990_000
        mtime = row["filepath"].stat().st_mtime if row["create_file"] else 1748000000.0
        cur.execute(
            """
            INSERT OR IGNORE INTO processed_state (
                stage, filepath, file_size, file_mtime, status, processed_at, reason
            ) VALUES (?, ?, ?, ?, ?, ?, '')
            """,
            ("organize", fp, size, mtime, "done", row["processed_at"]),
        )

    # duplicate_groups rows for the seeded duplicate pairs
    dup_pairs = 0
    for idx, row in enumerate(plan):
        if row["kind"] == "dup_copy":
            original = plan[row["dup_of"]]
            cur.execute(
                """
                INSERT INTO duplicate_groups (run_id, original, duplicate, reason, resolved)
                VALUES (NULL, ?, ?, ?, 0)
                """,
                (str(original["filepath"]), str(row["filepath"]),
                 "same artist/title, lower bitrate copy"),
            )
            dup_pairs += 1

    conn.commit()
    conn.close()

    # --- enrichment review queue (exact pipeline JSONL format) -----------------
    queue_path = root / "data" / "intelligence" / "enrichment_review_queue.jsonl"
    candidates = [r for r in plan if r["kind"] in ("clean", "junk_meta", "missing_meta")
                  and r["create_file"]][:24]
    entries = []
    for n, row in enumerate(candidates):
        if n < 6:
            confidence, action, score = "HIGH", "auto_candidate", round(0.92 + n * 0.01, 2)
        elif n < 18:
            confidence, action, score = "MEDIUM", "review", round(0.76 + (n - 6) * 0.01, 2)
        else:
            confidence, action, score = "LOW", "ignore", round(0.30 + (n - 18) * 0.05, 2)
        provider = ["spotify", "deezer", "traxsource"][n % 3]
        entries.append({
            "filepath": str(row["filepath"]),
            "query": {"artist": row["artist"] or "", "title": row["title"] or ""},
            "best_match": {
                "provider": provider,
                "artist": (row["artist"] or "Unknown").replace(" [promo]", ""),
                "title": (row["title"] or "Untitled").split(" (Official")[0].split(" [FREE")[0],
                "album": row["album"] or "Single",
                "year": 2020 + (n % 6),
            },
            "score": score,
            "confidence": confidence,
            "provider": provider,
            "action_suggestion": action,
            "timestamp": (BASE_TIME + timedelta(hours=n)).isoformat(),
        })
    queue_path.write_text(
        "\n".join(json.dumps(e, sort_keys=True) for e in entries) + "\n",
        encoding="utf-8",
    )

    # --- genuine pipeline scans (real proposal generation, read-only + queue files)
    env = dict(os.environ)
    scan_results = {}
    for command in (
        ["metadata-repair-scan", "--root", str(root)],
        ["metadata-sanitation-scan", "--root", str(root)],
        ["path-audit", "--root", str(root)],
    ):
        proc = subprocess.run(
            [sys.executable, str(PROJECT_ROOT / "pipeline.py"), *command],
            capture_output=True, text=True, env=env, cwd=str(PROJECT_ROOT),
        )
        scan_results[command[0]] = proc.returncode

    print("Fixture library seeded")
    print(f"  root              : {root}")
    print(f"  tracks in DB      : {len(plan)}")
    print(f"  files on disk     : {created_files}")
    print(f"  untracked files   : {len(untracked)}")
    print(f"  quarantined files : {len(quarantined)}")
    print(f"  duplicate pairs   : {dup_pairs}")
    print(f"  enrichment queue  : {len(entries)} entries")
    for name, rc in scan_results.items():
        print(f"  {name:24s}: exit {rc}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default="/app/fixture_library")
    parser.add_argument("--force", action="store_true",
                        help="Replace an existing fixture root")
    args = parser.parse_args()
    root = Path(args.root).resolve()
    if root == Path("/") or len(root.parts) < 2:
        print("Refusing to use an unsafe root.")
        sys.exit(1)
    seed(root, args.force)

    # ensure the fixture SSD destination exists so sync preview works
    Path("/app/fixture_ssd/KKDJ").mkdir(parents=True, exist_ok=True)


if __name__ == "__main__":
    main()
